### ISSUE TITLE
Visualising spatial uncertainty in point observations

### ISSUE THREAD

**Issue by mjwestgate** [StatSocAus/oceaniaR-hack#16]
Biodiversity observations in databases such as the [Atlas of Living Australia](https://ala.org.au) are often recorded at an intentionally low level of spatial precision. This process - known as 'obfuscation' - helps hide populations of species that are at risk of extinction, or of being targeted by the illegal pet trade. 

When these points are displayed on a map, however, there is no indication of which points are precise to ~10m, and which have been generalised to a precision of ~10km. Instead, default mapping approaches give the false impression that all points are _equally_ precise, which leads to problems in the use and interpretation of that data. There are several possible solutions to this problem:

- Only displaying points when the zoom level is more coarse than their level of precision
- Only showing summarised data, such as hex maps
- Changing point properties (colour, size, opacity) depending on their level of precision
- Some combination of the above

What is unclear is whether any of these solutions can both display information as precisely as possible, and not be visually jarring or over-complex on the screen. Put differently: solutions that are simple lose information, solutions that are complex aren't pretty. 

We propose working collaboratively to test different visualisations to see whether a generalisable solution to this problem can be found.

**Comment by deanmarchiori** [comment]
Hi! Thanks for the topic suggestion. 

To help us prepare for the hackathon event it would be great to prepare a **quick 30-60 sec overview** of the topic to introduce it to the group on the day and seek interested collaborators. You can use the below prompts to help with this: 

## What is the headline idea? 
## What is the (realistic) outcome being aimed for during the event? 
## What types of contributions would be welcomed (i.e. specific skills, tasks)?

**Comment by daxkellie** [comment]
Just noting some good example species with a range of spatial precision:

- _Caladenia clavigera_ Plain-lip Spider-orchid
- _Callocephalon fimbriatum_ Gang-gang cockatoo
- _Pristis pristis_ Freshwater sawfish

**Comment by daxkellie** [comment]
In discussing this problem with the Atlas of Living Australia team, and I think we might not be quite ready to tackle this issue yet. This summarises the issue quite nicely:
![oh_no_success](https://github.com/user-attachments/assets/96456bd5-7ca4-45e8-ac39-d24b7247724c)
(Credit: Alex Norris [webcomicname.com](https://webcomicname.com/))

Suggest closing this for now as I don't think this problem is hackathon ready just yet 😞 
cc/ @mjwestgate
