### ISSUE TITLE
Build package that scrapes Australian house prices–with extensions

### ISSUE THREAD

**Issue by chitrams** [StatSocAus/oceaniaR-hack#20]
From this very simple (and scrape-able) website: http://house.speakingsame.com/

Potential extensions:

- Scrape rent prices, then create a tool so one can figure out how much average rent is in the suburb they want (postcode, proximity to parks, schools etc) with the amenities they want (bedroom, bathroom, parking)
- Create a tool so one can figure out average price for a property they want
- Adjust for inflation over time too

**Comment by deanmarchiori** [comment]
Hi! Thanks for the topic suggestion. 

To help us prepare for the hackathon event it would be great to prepare a **quick 30-60 sec overview** of the topic to introduce it to the group on the day and seek interested collaborators. You can use the below prompts to help with this: 

## What is the headline idea? 
## What is the (realistic) outcome being aimed for during the event? 
## What types of contributions would be welcomed (i.e. specific skills, tasks)?

**Comment by chitrams** [comment]
Website doesn't work so probably not going to work on this
